name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Build frontend_next
        run: deno task build --platform=deno-deploy

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: aleph
          entrypoint: dist/server.js